-- ============================================
-- DONNÉES FICTIVES CAMEROUNAISES - SOLITIQUO
-- Compatible avec backend/database/schema.sql
-- ============================================

-- ============================================
-- 1. ARTICLES (12 articles)
-- ============================================

INSERT INTO articles (title, slug, content, excerpt, featured_image, author_id, category, tags, status, is_premium, language, views_count, published_at, created_at, updated_at) VALUES

-- POLITIQUE (4 articles dont 1 premium)
('La réforme constitutionnelle de 2026 : enjeux et perspectives',
'reforme-constitutionnelle-2026-enjeux-perspectives',
'<h2>Introduction</h2><p>Le projet de réforme constitutionnelle présenté par le gouvernement camerounais soulève de nombreux débats au sein de la classe politique et de la société civile. Cette réforme, annoncée comme une étape majeure vers la modernisation des institutions, propose notamment une limitation du nombre de mandats présidentiels et un renforcement des pouvoirs du Parlement.</p><h2>Les points clés de la réforme</h2><p>Parmi les mesures phares, on retrouve la création d''un poste de Vice-Président, le renforcement de l''indépendance de la justice, et l''instauration d''un Sénat réellement fonctionnel. Ces changements visent à répondre aux aspirations démocratiques exprimées lors des dernières élections.</p><h2>Réactions de l''opposition</h2><p>Les partis d''opposition restent divisés sur cette réforme. Certains y voient une avancée significative, tandis que d''autres dénoncent une réforme cosmétique destinée à maintenir le statu quo.</p>',
'Le projet de réforme constitutionnelle divise la classe politique camerounaise. Entre espoirs de modernisation et craintes de manipulation, analyse des enjeux.',
'https://images.unsplash.com/photo-1541872703-74c5e44368f9?w=800',
1,
'Politique',
ARRAY['constitution', 'réforme', 'démocratie', 'institutions'],
'published',
FALSE,
'fr',
156,
NOW() - INTERVAL '2 days',
NOW() - INTERVAL '2 days',
NOW() - INTERVAL '2 days'),

('Élections municipales 2026 : la bataille de Douala',
'elections-municipales-2026-bataille-douala',
'<h2>Un scrutin sous haute tension</h2><p>À quelques mois des élections municipales, la ville de Douala se prépare à un scrutin qui s''annonce particulièrement disputé. Les trois principaux candidats à la mairie ont lancé leurs campagnes avec des programmes ambitieux axés sur le développement urbain, la gestion des déchets et la mobilité.</p><h2>Les candidats en lice</h2><p>Le maire sortant, Jean-Pierre Essomba, se présente pour un troisième mandat en mettant en avant son bilan en matière d''infrastructures. Face à lui, Marie-Claire Ngono, ancienne députée, promet une gestion plus transparente et participative. Le troisième candidat, Paul Ateba, entrepreneur prospère, mise sur son expérience du secteur privé.</p>',
'La capitale économique se prépare à des élections municipales décisives. Trois candidats, trois visions pour l''avenir de Douala.',
'https://images.unsplash.com/photo-1555858509-e9c76c22b6f2?w=800',
1,
'Politique',
ARRAY['élections', 'municipales', 'douala', 'campagne'],
'published',
FALSE,
'fr',
203,
NOW() - INTERVAL '5 days',
NOW() - INTERVAL '5 days',
NOW() - INTERVAL '5 days'),

('🔒 PREMIUM : Décentralisation au Cameroun, quelles perspectives ?',
'decentralisation-cameroun-perspectives-premium',
'<h2>Un processus en marche depuis 2010</h2><p>La décentralisation, inscrite dans la Constitution camerounaise depuis 1996, n''a réellement commencé à se concrétiser qu''à partir de 2010 avec la création des régions. Aujourd''hui, le transfert des compétences et des ressources aux collectivités territoriales progresse, mais de nombreux défis subsistent.</p><h2>Les défis financiers</h2><p>Le principal obstacle reste le financement. Les régions et communes peinent à mobiliser les ressources nécessaires pour assumer leurs nouvelles compétences. Le gouvernement central transfère seulement 15% du budget national aux collectivités, un montant jugé insuffisant par les élus locaux.</p><h2>Renforcement des capacités</h2><p>Au-delà des finances, c''est la formation des cadres locaux qui pose question. De nombreux agents territoriaux manquent d''expertise en gestion de projets et en finances publiques. Des programmes de formation sont en cours, soutenus par des partenaires internationaux.</p><h2>Opportunités de développement</h2><p>Malgré ces difficultés, la décentralisation représente une opportunité unique pour impulser un développement territorial équilibré. Les régions du Nord et de l''Extrême-Nord, longtemps marginalisées, peuvent désormais définir leurs propres priorités de développement.</p>',
'Analyse approfondie du processus de décentralisation camerounais : défis, opportunités et recommandations pour un développement territorial équilibré. Article premium.',
'https://images.unsplash.com/photo-1589829085413-56de8ae18c73?w=800',
1,
'Politique',
ARRAY['décentralisation', 'gouvernance', 'régions', 'premium'],
'published',
TRUE,
'fr',
89,
NOW() - INTERVAL '1 day',
NOW() - INTERVAL '1 day',
NOW() - INTERVAL '1 day'),

('Le dialogue national : entre espoirs et scepticisme',
'dialogue-national-espoirs-scepticisme',
'<h2>Un rendez-vous attendu</h2><p>Le gouvernement a annoncé l''organisation d''un dialogue national inclusif pour aborder les questions de gouvernance, de cohésion sociale et de développement économique. Cette initiative intervient dans un contexte de tensions politiques et sociales.</p><h2>Les thématiques au cœur des débats</h2><p>Parmi les sujets prioritaires figurent la crise anglophone, la jeunesse et l''emploi, ainsi que la corruption. Les organisations de la société civile ont salué cette démarche tout en appelant à une participation effective de toutes les composantes de la nation.</p>',
'Le dialogue national camerounais s''annonce comme un moment crucial. Entre attentes de la population et défis organisationnels, décryptage d''un processus complexe.',
'https://images.unsplash.com/photo-1540910419892-4a36d2c3266c?w=800',
1,
'Politique',
ARRAY['dialogue', 'national', 'gouvernance', 'cohésion'],
'published',
FALSE,
'fr',
178,
NOW() - INTERVAL '7 days',
NOW() - INTERVAL '7 days',
NOW() - INTERVAL '7 days'),

-- SOCIAL (4 articles dont 1 premium)
('Éducation : la crise des enseignants au Cameroun',
'education-crise-enseignants-cameroun',
'<h2>Un système sous pression</h2><p>Le système éducatif camerounais fait face à une crise majeure avec un déficit de plus de 50 000 enseignants, particulièrement dans les zones rurales. Cette situation compromet la qualité de l''enseignement et l''avenir de milliers d''élèves.</p><h2>Les causes du problème</h2><p>Faible attractivité du métier, salaires peu compétitifs, conditions de travail difficiles : les raisons de cette pénurie sont multiples. De nombreux enseignants qualifiés préfèrent s''orienter vers le secteur privé ou l''étranger.</p><h2>Les initiatives gouvernementales</h2><p>Le ministère de l''Éducation a annoncé le recrutement de 30 000 enseignants sur trois ans et une revalorisation progressive des salaires. Des programmes de formation accélérée sont également mis en place.</p>',
'La pénurie d''enseignants menace l''avenir éducatif du Cameroun. État des lieux d''une crise qui touche particulièrement les zones rurales.',
'https://images.unsplash.com/photo-1503676260728-1c00da094a0b?w=800',
1,
'Social',
ARRAY['éducation', 'enseignants', 'école', 'formation'],
'published',
FALSE,
'fr',
234,
NOW() - INTERVAL '3 days',
NOW() - INTERVAL '3 days',
NOW() - INTERVAL '3 days'),

('Santé : l''hôpital public camerounais en quête de modernisation',
'sante-hopital-public-modernisation',
'<h2>Des infrastructures vieillissantes</h2><p>Les hôpitaux publics camerounais font face à de nombreux défis : équipements obsolètes, manque de médicaments, personnel insuffisant. Cette situation pousse de nombreux Camerounais à se tourner vers les cliniques privées, souvent inaccessibles financièrement.</p><h2>Le plan de réhabilitation</h2><p>Le gouvernement a lancé un vaste programme de modernisation des hôpitaux de référence. Budget alloué : 150 milliards de FCFA sur cinq ans. L''objectif est de doter chaque région d''au moins un hôpital de niveau international.</p>',
'Entre défis structurels et ambitions de modernisation, l''hôpital public camerounais tente de se réinventer pour mieux servir la population.',
'https://images.unsplash.com/photo-1519494026892-80bbd2d6fd0d?w=800',
1,
'Social',
ARRAY['santé', 'hôpital', 'modernisation', 'soins'],
'published',
FALSE,
'fr',
167,
NOW() - INTERVAL '4 days',
NOW() - INTERVAL '4 days',
NOW() - INTERVAL '4 days'),

('🔒 PREMIUM : Emploi des jeunes : la bombe à retardement camerounaise',
'emploi-jeunes-bombe-retardement-premium',
'<h2>Une jeunesse nombreuse et sans perspectives</h2><p>Avec 60% de la population âgée de moins de 25 ans, le Cameroun dispose d''un potentiel démographique considérable. Mais cette richesse se transforme en bombe sociale : le taux de chômage des jeunes dépasse 40% dans les zones urbaines.</p><h2>Les secteurs porteurs d''emplois</h2><p>L''agriculture modernisée, le numérique, l''artisanat et le tourisme sont identifiés comme des secteurs à fort potentiel. Le gouvernement mise sur la formation professionnelle et l''entrepreneuriat pour absorber cette main-d''œuvre jeune.</p><h2>Les programmes d''accompagnement</h2><p>Plusieurs dispositifs ont été créés : le Plan Triennal Jeunes (PLANUT), le Fonds National de l''Emploi (FNE), et plus récemment le programme Digital Cameroun qui vise à former 100 000 jeunes aux métiers du numérique d''ici 2028.</p><h2>Les défis à relever</h2><p>Au-delà des formations, c''est tout l''écosystème entrepreneurial qui doit être repensé : accès au financement, simplification administrative, création d''incubateurs dans toutes les régions.</p>',
'Face à un chômage massif des jeunes, le Cameroun cherche des solutions. Analyse des programmes, des défis et des opportunités. Contenu premium exclusif.',
'https://images.unsplash.com/photo-1522071820081-009f0129c71c?w=800',
1,
'Social',
ARRAY['emploi', 'jeunes', 'chômage', 'formation', 'premium'],
'published',
TRUE,
'fr',
145,
NOW() - INTERVAL '6 days',
NOW() - INTERVAL '6 days',
NOW() - INTERVAL '6 days'),

('Logement social : Yaoundé lance un programme ambitieux',
'logement-social-yaounde-programme',
'<h2>10 000 logements sociaux en trois ans</h2><p>La Communauté Urbaine de Yaoundé vient de lancer son programme de construction de logements sociaux. Objectif : résorber le déficit estimé à plus de 100 000 logements dans la capitale.</p><h2>Des critères d''attribution transparents</h2><p>Les bénéficiaires seront sélectionnés sur dossier, en privilégiant les familles modestes et les jeunes ménages. Le prix de vente est plafonné à 15 millions de FCFA pour un F3.</p>',
'Yaoundé s''attaque à la crise du logement avec un programme ambitieux. Entre promesses politiques et réalité du terrain, que peut-on espérer ?',
'https://images.unsplash.com/photo-1560518883-ce09059eeffa?w=800',
1,
'Social',
ARRAY['logement', 'social', 'yaoundé', 'habitation'],
'published',
FALSE,
'fr',
192,
NOW() - INTERVAL '8 days',
NOW() - INTERVAL '8 days',
NOW() - INTERVAL '8 days'),

-- ÉCONOMIE (3 articles)
('Économie numérique : le Cameroun attire les investisseurs',
'economie-numerique-cameroun-investisseurs',
'<h2>Un écosystème tech en pleine expansion</h2><p>Douala et Yaoundé voient fleurir les startups technologiques. Le secteur de la fintech notamment connaît une croissance spectaculaire avec l''émergence de solutions de paiement mobile adaptées au contexte local.</p><h2>Les hubs d''innovation</h2><p>Plusieurs incubateurs et accélérateurs accompagnent les entrepreneurs : Silicon Mountain à Buéa, ActivSpaces à Douala et Yaoundé, Entrepreneurial Lab. Ces structures offrent mentorat, financement et mise en réseau.</p><h2>Les défis à surmonter</h2><p>Malgré cette dynamique positive, des obstacles persistent : connexion internet instable, coût élevé de la bande passante, difficulté d''accès au financement pour les phases d''amorçage.</p>',
'Le Cameroun s''impose progressivement comme un hub tech en Afrique centrale. Zoom sur un écosystème numérique en pleine effervescence.',
'https://images.unsplash.com/photo-1460925895917-afdab827c52f?w=800',
1,
'Économie',
ARRAY['numérique', 'tech', 'startups', 'innovation'],
'published',
FALSE,
'fr',
211,
NOW() - INTERVAL '9 days',
NOW() - INTERVAL '9 days',
NOW() - INTERVAL '9 days'),

('Agriculture : la transformation locale s''accélère',
'agriculture-transformation-locale',
'<h2>De la production à la transformation</h2><p>Le Cameroun, grenier de l''Afrique centrale, renforce sa stratégie d''industrialisation agricole. De nombreuses unités de transformation voient le jour : huileries, chocolateries, unités de conditionnement de fruits.</p><h2>L''exemple du cacao</h2><p>Premier producteur d''Afrique centrale avec 280 000 tonnes par an, le Cameroun veut transformer localement 50% de sa production d''ici 2030. Plusieurs chocolateries camerounaises exportent désormais vers l''Europe et l''Asie.</p>',
'Du champ à l''usine : le Cameroun mise sur la transformation locale de ses produits agricoles pour créer de la valeur ajoutée et des emplois.',
'https://images.unsplash.com/photo-1625246333195-78d9c38ad449?w=800',
1,
'Économie',
ARRAY['agriculture', 'transformation', 'cacao', 'export'],
'published',
FALSE,
'fr',
188,
NOW() - INTERVAL '10 days',
NOW() - INTERVAL '10 days',
NOW() - INTERVAL '10 days'),

('Infrastructures : le méga-projet du port en eau profonde de Kribi',
'infrastructures-port-kribi',
'<h2>Un projet stratégique pour l''Afrique centrale</h2><p>Le port en eau profonde de Kribi, dont la deuxième phase vient d''être inaugurée, ambitionne de devenir le hub logistique de référence en Afrique centrale. Capacité actuelle : 15 millions de tonnes par an.</p><h2>Impacts économiques</h2><p>Au-delà du désenclavement, ce projet génère des milliers d''emplois directs et indirects. La zone industrielle adjacente attire déjà des investisseurs dans les secteurs de la transformation du bois, de l''agro-industrie et de la logistique.</p>',
'Le port de Kribi transforme l''économie camerounaise. Analyse d''un projet d''envergure régionale qui repositionne le Cameroun dans le commerce international.',
'https://images.unsplash.com/photo-1605902711834-8b11c3e3ef2f?w=800',
1,
'Économie',
ARRAY['infrastructures', 'port', 'kribi', 'logistique'],
'published',
FALSE,
'fr',
176,
NOW() - INTERVAL '11 days',
NOW() - INTERVAL '11 days',
NOW() - INTERVAL '11 days'),

-- INTERNATIONAL (1 article)
('Diplomatie : le Cameroun renforce ses liens avec l''Asie',
'diplomatie-cameroun-asie',
'<h2>Une stratégie de diversification</h2><p>Face aux mutations géopolitiques mondiales, le Cameroun intensifie ses relations avec les pays asiatiques, notamment la Chine, l''Inde et le Vietnam. Ces partenariats couvrent les domaines des infrastructures, de l''éducation et du commerce.</p><h2>Les grands projets sino-camerounais</h2><p>La Chine est devenue le premier partenaire commercial du Cameroun. Plusieurs projets structurants sont financés par Pékin : barrages hydroélectriques, routes, stades. Cette coopération suscite néanmoins des débats sur l''endettement du pays.</p>',
'Entre opportunités économiques et questionnements sur la souveraineté, la coopération avec l''Asie redessine la diplomatie camerounaise.',
'https://images.unsplash.com/photo-1451187580459-43490279c0fa?w=800',
1,
'International',
ARRAY['diplomatie', 'asie', 'chine', 'commerce'],
'published',
FALSE,
'fr',
154,
NOW() - INTERVAL '12 days',
NOW() - INTERVAL '12 days',
NOW() - INTERVAL '12 days');

-- ============================================
-- 2. PODCASTS (14 podcasts)
-- ============================================

INSERT INTO podcasts (title, slug, description, audio_url, duration_seconds, cover_image, author_id, category, tags, status, is_premium, plays_count, published_at, created_at, updated_at) VALUES

('Débat politique #12 : Réforme constitutionnelle',
'debat-politique-12-reforme-constitutionnelle',
'Analyse approfondie de la réforme constitutionnelle avec nos experts. Quels changements pour les institutions camerounaises ? Décryptage des enjeux et des oppositions.',
'https://www.soundhelix.com/examples/mp3/SoundHelix-Song-1.mp3',
1845,
'https://images.unsplash.com/photo-1589903308904-1010c2294adc?w=600',
1,
'Politique',
ARRAY['débat', 'constitution', 'politique'],
'published',
FALSE,
342,
NOW() - INTERVAL '1 day',
NOW() - INTERVAL '1 day',
NOW()),

('Éco Talk : L''essor du numérique au Cameroun',
'eco-talk-essor-numerique-cameroun',
'Rencontre avec trois entrepreneurs de la tech camerounaise qui racontent leur parcours, les défis du secteur et les opportunités à saisir.',
'https://www.soundhelix.com/examples/mp3/SoundHelix-Song-2.mp3',
2134,
'https://images.unsplash.com/photo-1590650516494-0c8e4a4dd67e?w=600',
1,
'Économie',
ARRAY['économie', 'numérique', 'tech', 'startups'],
'published',
FALSE,
278,
NOW() - INTERVAL '2 days',
NOW() - INTERVAL '2 days',
NOW()),

('Société : La jeunesse camerounaise face à l''emploi',
'societe-jeunesse-camerounaise-emploi',
'Témoignages de jeunes diplômés, analyse du marché de l''emploi, solutions innovantes : un podcast pour comprendre les défis de la jeunesse.',
'https://www.soundhelix.com/examples/mp3/SoundHelix-Song-3.mp3',
1678,
'https://images.unsplash.com/photo-1516280440614-37939bbacd81?w=600',
1,
'Social',
ARRAY['jeunes', 'emploi', 'chômage'],
'published',
FALSE,
456,
NOW() - INTERVAL '3 days',
NOW() - INTERVAL '3 days',
NOW()),

('Culture : Le cinéma camerounais à l''honneur',
'culture-cinema-camerounais',
'Portrait de la nouvelle génération de cinéastes camerounais qui fait rayonner le 7e art national sur la scène internationale.',
'https://www.soundhelix.com/examples/mp3/SoundHelix-Song-4.mp3',
1423,
'https://images.unsplash.com/photo-1485846234645-a62644f84728?w=600',
1,
'Culture',
ARRAY['culture', 'cinéma', 'art'],
'published',
FALSE,
189,
NOW() - INTERVAL '4 days',
NOW() - INTERVAL '4 days',
NOW()),

('Santé : Les défis du système hospitalier',
'sante-defis-systeme-hospitalier',
'Discussion avec des professionnels de santé sur l''état des hôpitaux, les réformes nécessaires et les solutions pour améliorer l''accès aux soins.',
'https://www.soundhelix.com/examples/mp3/SoundHelix-Song-5.mp3',
1956,
'https://images.unsplash.com/photo-1538108149393-fbbd81895907?w=600',
1,
'Social',
ARRAY['santé', 'hôpital', 'soins'],
'published',
FALSE,
312,
NOW() - INTERVAL '5 days',
NOW() - INTERVAL '5 days',
NOW()),

('Agriculture : De la ferme à l''assiette',
'agriculture-ferme-assiette',
'Zoom sur les initiatives d''agriculture durable au Cameroun et les circuits courts qui transforment la production locale.',
'https://www.soundhelix.com/examples/mp3/SoundHelix-Song-6.mp3',
1789,
'https://images.unsplash.com/photo-1625246333195-78d9c38ad449?w=600',
1,
'Économie',
ARRAY['agriculture', 'durable', 'local'],
'published',
FALSE,
234,
NOW() - INTERVAL '6 days',
NOW() - INTERVAL '6 days',
NOW()),

('Éducation : Réformer l''école camerounaise',
'education-reformer-ecole-camerounaise',
'Enseignants, parents et élèves s''expriment sur les forces et faiblesses du système éducatif. Quelles pistes pour l''avenir ?',
'https://www.soundhelix.com/examples/mp3/SoundHelix-Song-7.mp3',
2012,
'https://images.unsplash.com/photo-1503676260728-1c00da094a0b?w=600',
1,
'Social',
ARRAY['éducation', 'école', 'réforme'],
'published',
FALSE,
401,
NOW() - INTERVAL '7 days',
NOW() - INTERVAL '7 days',
NOW()),

('Décentralisation : Le pouvoir aux régions',
'decentralisation-pouvoir-regions',
'Décryptage du processus de décentralisation avec des élus locaux et des experts en gouvernance territoriale.',
'https://www.soundhelix.com/examples/mp3/SoundHelix-Song-8.mp3',
1634,
'https://images.unsplash.com/photo-1589829085413-56de8ae18c73?w=600',
1,
'Politique',
ARRAY['décentralisation', 'régions', 'gouvernance'],
'published',
FALSE,
267,
NOW() - INTERVAL '8 days',
NOW() - INTERVAL '8 days',
NOW()),

('Sport : Le football camerounais en mutation',
'sport-football-camerounais-mutation',
'Analyse du championnat national, des défis de la fédération et des espoirs olympiques pour Paris 2024.',
'https://www.soundhelix.com/examples/mp3/SoundHelix-Song-9.mp3',
1467,
'https://images.unsplash.com/photo-1579952363873-27f3bade9f55?w=600',
1,
'Sport',
ARRAY['sport', 'football', 'championnat'],
'published',
FALSE,
523,
NOW() - INTERVAL '9 days',
NOW() - INTERVAL '9 days',
NOW()),

('International : Le Cameroun sur la scène africaine',
'international-cameroun-scene-africaine',
'Position diplomatique du Cameroun, relations avec les voisins, rôle au sein de la CEMAC : décryptage géopolitique.',
'https://www.soundhelix.com/examples/mp3/SoundHelix-Song-10.mp3',
1890,
'https://images.unsplash.com/photo-1451187580459-43490279c0fa?w=600',
1,
'International',
ARRAY['international', 'diplomatie', 'afrique'],
'published',
FALSE,
198,
NOW() - INTERVAL '10 days',
NOW() - INTERVAL '10 days',
NOW()),

-- PODCASTS NATIFS DES PARTIS
('RDPC : Notre vision pour le Cameroun',
'rdpc-vision-cameroun',
'Podcast officiel du Rassemblement Démocratique du Peuple Camerounais. Présentation du programme politique et des réalisations du parti.',
'https://www.soundhelix.com/examples/mp3/SoundHelix-Song-11.mp3',
1234,
'https://images.unsplash.com/photo-1541872703-74c5e44368f9?w=600',
1,
'Politique',
ARRAY['RDPC', 'parti', 'programme'],
'published',
FALSE,
156,
NOW() - INTERVAL '15 days',
NOW() - INTERVAL '15 days',
NOW()),

('SDF : L''alternative démocratique',
'sdf-alternative-democratique',
'Le Social Democratic Front présente ses propositions pour une gouvernance inclusive et transparente au Cameroun.',
'https://www.soundhelix.com/examples/mp3/SoundHelix-Song-12.mp3',
1567,
'https://images.unsplash.com/photo-1555858509-e9c76c22b6f2?w=600',
1,
'Politique',
ARRAY['SDF', 'parti', 'démocratie'],
'published',
FALSE,
143,
NOW() - INTERVAL '14 days',
NOW() - INTERVAL '14 days',
NOW()),

('MRC : Le mouvement pour la renaissance',
'mrc-mouvement-renaissance',
'Podcast du Mouvement pour la Renaissance du Cameroun. Analyses, propositions et débats sur l''avenir du pays.',
'https://www.soundhelix.com/examples/mp3/SoundHelix-Song-13.mp3',
1398,
'https://images.unsplash.com/photo-1540910419892-4a36d2c3266c?w=600',
1,
'Politique',
ARRAY['MRC', 'parti', 'renaissance'],
'published',
FALSE,
289,
NOW() - INTERVAL '13 days',
NOW() - INTERVAL '13 days',
NOW()),

('UNDP : Unis pour le développement',
'undp-unis-developpement',
'L''Union Nationale pour la Démocratie et le Progrès expose sa vision d''un Cameroun prospère et équitable.',
'https://www.soundhelix.com/examples/mp3/SoundHelix-Song-14.mp3',
1445,
'https://images.unsplash.com/photo-1589829085413-56de8ae18c73?w=600',
1,
'Politique',
ARRAY['UNDP', 'parti', 'développement'],
'published',
FALSE,
167,
NOW() - INTERVAL '12 days',
NOW() - INTERVAL '12 days',
NOW());

-- ============================================
-- 3. ÉMISSIONS VIDÉO (4 vidéos)
-- ============================================

INSERT INTO emissions (title, slug, description, video_url, thumbnail_url, duration_seconds, host_id, status, is_premium, views_count, aired_at, created_at, updated_at) VALUES

('Le Grand Débat : Élections municipales 2026',
'grand-debat-elections-municipales-2026',
'Face-à-face entre les trois principaux candidats à la mairie de Douala. Un débat animé sur les enjeux urbains, la gestion publique et les projets de développement.',
'https://www.youtube.com/watch?v=9bZkp7q19f0',
'https://img.youtube.com/vi/9bZkp7q19f0/maxresdefault.jpg',
3615,
1,
'published',
FALSE,
487,
NOW() - INTERVAL '3 days',
NOW() - INTERVAL '3 days',
NOW()),

('Reportage : Dans les coulisses du port de Kribi',
'reportage-coulisses-port-kribi',
'Découverte exclusive des infrastructures du port en eau profonde. Rencontre avec les travailleurs, les gestionnaires et les entreprises qui font vivre ce hub stratégique.',
'https://www.youtube.com/watch?v=aqz-KE-bpKQ',
'https://img.youtube.com/vi/aqz-KE-bpKQ/maxresdefault.jpg',
2847,
1,
'published',
FALSE,
312,
NOW() - INTERVAL '5 days',
NOW() - INTERVAL '5 days',
NOW()),

('🎵 EXCLUSIF : Message important du gouvernement',
'exclusif-message-important-gouvernement',
'Une annonce spéciale concernant l''avenir politique du Cameroun. À ne manquer sous aucun prétexte ! 🔥',
'https://www.youtube.com/watch?v=dQw4w9WgXcQ',
'https://img.youtube.com/vi/dQw4w9WgXcQ/maxresdefault.jpg',
212,
1,
'published',
FALSE,
1456,
NOW() - INTERVAL '1 day',
NOW() - INTERVAL '1 day',
NOW()),

('Documentaire : Les oubliés de la crise anglophone',
'documentaire-oublies-crise-anglophone',
'Reportage poignant sur les populations déplacées par la crise dans les régions anglophones. Témoignages, analyses et pistes de solutions pour la réconciliation nationale.',
'https://www.youtube.com/watch?v=jNQXAC9IVRw',
'https://img.youtube.com/vi/jNQXAC9IVRw/maxresdefault.jpg',
4125,
1,
'published',
FALSE,
678,
NOW() - INTERVAL '7 days',
NOW() - INTERVAL '7 days',
NOW());

-- ============================================
-- FIN DU SCRIPT
-- Total : 12 articles + 14 podcasts + 4 vidéos
-- ============================================
